#!/usr/bin/env bash
# =============================================================================
# Tidefly Agent Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/tidefly-oss/tidefly-agent/main/scripts/install.sh | sh
# Or with token: PLANE_ENDPOINT=plane.example.com:7443 PLANE_TOKEN=tfy_reg_xxx ... | sh
# =============================================================================
set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
REPO="tidefly-oss/tidefly-agent"
BINARY="tidefly-agent"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/tidefly-agent"
SERVICE_FILE="/etc/systemd/system/tidefly-agent.service"
ENV_FILE="$CONFIG_DIR/.env"

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    { echo -e "${BLUE}[tidefly]${NC} $*"; }
success() { echo -e "${GREEN}[tidefly]${NC} $*"; }
warn()    { echo -e "${YELLOW}[tidefly]${NC} $*"; }
error()   { echo -e "${RED}[tidefly]${NC} $*" >&2; exit 1; }

# ── Root check ────────────────────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
  error "This installer must be run as root. Try: sudo sh"
fi

# ── Detect OS / Arch ──────────────────────────────────────────────────────────
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)  ARCH="amd64" ;;
  aarch64) ARCH="arm64" ;;
  armv7l)  ARCH="arm"   ;;
  *)       error "Unsupported architecture: $ARCH" ;;
esac

if [ "$OS" != "linux" ]; then
  error "Only Linux is supported. Got: $OS"
fi

# ── Detect latest version ─────────────────────────────────────────────────────
info "Fetching latest release..."
VERSION="${TIDEFLY_AGENT_VERSION:-}"
if [ -z "$VERSION" ]; then
  VERSION=$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" \
    | grep '"tag_name"' | sed 's/.*"tag_name": *"\(.*\)".*/\1/')
fi

if [ -z "$VERSION" ]; then
  error "Could not determine latest version. Set TIDEFLY_AGENT_VERSION manually."
fi

info "Installing tidefly-agent $VERSION ($OS/$ARCH)"

# ── Download binary ───────────────────────────────────────────────────────────
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

DOWNLOAD_URL="https://github.com/$REPO/releases/download/$VERSION/tidefly-agent_${OS}_${ARCH}.tar.gz"
info "Downloading from $DOWNLOAD_URL"

curl -fsSL "$DOWNLOAD_URL" -o "$TMP_DIR/tidefly-agent.tar.gz" \
  || error "Download failed. Check the URL or your internet connection."

tar -xzf "$TMP_DIR/tidefly-agent.tar.gz" -C "$TMP_DIR"
chmod +x "$TMP_DIR/$BINARY"
mv "$TMP_DIR/$BINARY" "$INSTALL_DIR/$BINARY"

success "Binary installed to $INSTALL_DIR/$BINARY"

# ── Create config dir ─────────────────────────────────────────────────────────
mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

# ── Write .env if not exists ──────────────────────────────────────────────────
if [ ! -f "$ENV_FILE" ]; then
  # Generate a stable agent ID
  AGENT_ID="$(cat /proc/sys/kernel/random/uuid 2>/dev/null || uuidgen)"
  AGENT_NAME="${AGENT_NAME:-$(hostname)}"

  cat > "$ENV_FILE" << EOF
# Tidefly Agent Configuration
# Generated by installer on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Agent Identity ─────────────────────────────────────────────
AGENT_ID=$AGENT_ID
AGENT_NAME=$AGENT_NAME

# ── Plane Connection ───────────────────────────────────────────
# gRPC endpoint of your Tidefly Plane (host:port)
PLANE_ENDPOINT=${PLANE_ENDPOINT:-}

# One-time registration token (generate in Tidefly UI → Servers → Add Server)
# Remove this line after first successful registration
PLANE_TOKEN=${PLANE_TOKEN:-}

# HTTP endpoint of your Tidefly Plane (for registration request)
# Leave empty to auto-derive from PLANE_ENDPOINT
PLANE_HTTP_ENDPOINT=${PLANE_HTTP_ENDPOINT:-}

# ── Certificate Paths ──────────────────────────────────────────
PLANE_CERT_FILE=$CONFIG_DIR/client.crt
PLANE_KEY_FILE=$CONFIG_DIR/client.key
PLANE_CA_FILE=$CONFIG_DIR/ca.crt

# ── Runtime ────────────────────────────────────────────────────
RUNTIME_TYPE=docker
RUNTIME_SOCKET=/var/run/docker.sock

# ── Caddy (local reverse proxy on this worker) ─────────────────
CADDY_ENABLED=true
CADDY_ADMIN_URL=http://127.0.0.1:2019

# ── Logging ────────────────────────────────────────────────────
LOG_LEVEL=info
EOF
  chmod 600 "$ENV_FILE"
  success "Config written to $ENV_FILE"
else
  warn "Config already exists at $ENV_FILE — skipping"
fi

# ── Validate required config ──────────────────────────────────────────────────
# shellcheck disable=SC1090
. "$ENV_FILE"

if [ -z "${PLANE_ENDPOINT:-}" ]; then
  warn ""
  warn "PLANE_ENDPOINT is not set in $ENV_FILE"
  warn "Edit the config before starting the agent:"
  warn "  $ENV_FILE"
fi

# ── Install systemd service ───────────────────────────────────────────────────
if command -v systemctl > /dev/null 2>&1; then
  cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Tidefly Agent
Documentation=https://github.com/tidefly-oss/tidefly-agent
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=$CONFIG_DIR
EnvironmentFile=$ENV_FILE
ExecStart=$INSTALL_DIR/$BINARY
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=tidefly-agent

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable tidefly-agent

  success "Systemd service installed and enabled"
  info ""
  info "Next steps:"
  info "  1. Edit config:  nano $ENV_FILE"
  info "  2. Set PLANE_ENDPOINT and PLANE_TOKEN"
  info "  3. Start agent:  systemctl start tidefly-agent"
  info "  4. Check status: systemctl status tidefly-agent"
  info "  5. View logs:    journalctl -u tidefly-agent -f"
else
  warn "systemd not found — skipping service installation"
  info ""
  info "Start manually:"
  info "  $INSTALL_DIR/$BINARY"
fi

echo ""
success "tidefly-agent $VERSION installed successfully!"